export const knowledgeArray = [
    "define",
    "identify",
    "describe",
    "label",
    "list",
    "name",
    "state",
    "match",
    "recognize",
    "select",
    "examine",
    "locate",
    "memorize",
    "quote",
    "recall",
    "reproduce",
    "tabulate",
    "tell",
    "copy",
    "discover",
    "duplicate",
    "enumerate",
    "listen",
    "observe",
    "omit",
    "read",
    "recite",
    "record",
    "repeat",
    "retell",
    "visualize",
<<<<<<< HEAD
]
=======
    "remember"]
>>>>>>> 8a67b6d665f3ccf5d860c385a38396d98bb8e2e8
